name: wechat
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  firebase_storage: ^11.2.6
  emoji_picker_flutter: ^1.6.1
  firebase_messaging: ^14.6.6
  http: ^0.13.5
  flutter_notification_channel: ^2.0.0
  image_gallery_saver: ^2.0.3
  dio: ^5.3.2
  zego_uikit_prebuilt_call: ^3.12.3
  zego_uikit_signaling_plugin: ^2.3.2
  zego_uikit: ^2.9.3
  video_player: ^2.7.0
  video_editor: ^3.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/chat.png"
  min_sdk_android: 21
  remove_alpha_ios: true





flutter:


  uses-material-design: true


  assets:
     - images/

